### ISSUE TITLE
How to debug the js files?

### ISSUE THREAD

**Issue by saedrna** [m-schuetz/Skye#2]
Hi, 

Thanks for this awesome project. I am also working on a point clouds editing software, and this technique is very interesting to me.

I have managed to get the project work and show the point clouds. But my system is created in c++ environment, I need to port it to native OpenGL.

But I don't get a start point to debug the code and understand it.

Would you please kindly me let me know if there is a way to debug the rendering code? Or at least direct me some paths to understand the code.
I have done some digging and found that the core functions ```update()``` and ```render()``` are all coded in js files.

Regards,
Han

**Comment by m-schuetz** [comment]
Hi,

Yes, virtually all rendering is done in js. Unfortunately it's not possible to do breakpoint debugging in js because I didn't manage to connect our V8 integration to the V8/Node/Chrome debugging tools. From what I've previously read I believe that it could be possible to debug the JS code in chrome dev tools, Node.js manages to do it too, but I don't really know how.

You can, however, debug the C++ part. In Visual Studio, for example, you can add breakpoints to the JS<->C++ bindings of OpenGL functions in V8Helper.cpp and V8GLExtBindings.cpp. It won't tell you which line of js the function call originates from, though.

**Comment by saedrna** [comment]
Thanks, maybe I can only read the code. Is ```render_progressive.js``` the right place for me to start?

**Comment by m-schuetz** [comment]
Yes, render_progressive.js and some of the other files in modules/progressive. Some are dead code but render_progressive.js contains all the relevant render passes and references the necessary shader files.

**Comment by m-schuetz** [comment]
Capturing a frame with NVIDIA Nsight may also help you get an idea of the inputs and results of each pass in a frame.

**Comment by saedrna** [comment]
Aha! I will try this.
